name: LiveNotchXcodeSampleApp
options:
  deploymentTarget:
    macOS: "13.0"
schemes:
  LiveNotchXcodeSampleApp:
    build:
      targets:
        LiveNotchXcodeSampleApp: all
targets:
  LiveNotchXcodeSampleApp:
    type: application
    platform: macOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.LiveNotchXcodeSampleApp
      CODE_SIGN_STYLE: Automatic
    sources:
      - path: Sources/App
    info:
      path: Supporting/Info.plist
    dependencies:
      - package: LiveNotchExtensionKit
packages:
  LiveNotchExtensionKit:
    path: ../..
